<?php 
$animeData = [
    [
      'title' => 'The Apothecary Diaries Season 2',
      'image' => 'res/animeCover/apothecaryDiariesS2.png',
      'genre' => 'Historical, Mystery, Drama',
      'status' => 'Ongoing',
      'type' => 'TV Series',
      'rating' => '8.82',
      'episodes' => '12 episodes',
      'minutes_per_episode' => '24 min',
      'release_dates' => 'Jan 10, 2025 – Ongoing',
      'studio' => 'Madhouse',
      'source' => 'Manga',
      'popularity_rank' => 1008,
      'rating_rank' => 31,
      'people_added' => '260.6K users',
      'description' => 'Follows Maomao\'s intriguing journey within the inner palace, unraveling mysteries and navigating complex relationships.'
    ],
    [
      'title' => 'One Piece',
      'image' => 'res/animeCover/onePiece.png',
      'genre' => 'Action, Adventure, Fantasy',
      'status' => 'Ongoing',
      'type' => 'TV Series',
      'rating' => '8.73',
      'episodes' => 'Ongoing',
      'minutes_per_episode' => '24 min',
      'release_dates' => 'Oct 20, 1999 - Ongoing',
      'studio' => 'Toei Animation',
      'source' => 'Manga',
      'popularity_rank' => 17,
      'rating_rank' => 51,
      'people_added' => '2.5M users',
      'description' => 'The Straw Hat Pirates delve deeper into the mysteries of Egghead Island, encountering new allies and adversaries.'
    ],
    [
      'title' => 'To Be Hero X',
      'image' => 'res/animeCover/toBeHeroX.png',
      'genre' => 'Action, Comedy, Superhero',
      'status' => 'Ongoing',
      'type' => 'TV Series',
      'rating' => '8.51',
      'episodes' => '24 episodes',
      'minutes_per_episode' => '24 min',
      'release_dates' => 'April 6, 2025 - Ongoing',
      'studio' => 'Pb Animation Co. Ltd., LAN Studio, Paper Plane Animation Studio',
      'source' => 'Original',
      'popularity_rank' => 3409,
      'rating_rank' => 139,
      'people_added' => '48.3K users',
      'description' => 'A former hero, now living a mundane life, is thrust back into action, facing new challenges and foes.'
    ],
    [
      'title' => 'Heaven\'s Official Blessing Short Film',
      'image' => 'res/animeCover/heavensBlessingShortFilm.png',
      'genre' => 'Fantasy, Romance',
      'status' => 'Completed',
      'type' => 'Short Film',
      'rating' => '8.50',
      'episodes' => 'Ongoing',
      'minutes_per_episode' => '8 min',
      'release_dates' => 'Feb 12, 2025 - Ongoing',
      'studio' => 'Xenon Studios',
      'source' => 'Web Novel',
      'popularity_rank' => 8694,
      'rating_rank' => 144,
      'people_added' => '5.4K users',
      'description' => 'A beautifully animated short film depicting a romantic encounter in a celestial realm.'
    ],
    [
      'title' => 'Duopo Cangqiong: Nian Fan',
      'image' => 'res/animeCover/duopoCangqiongNianFan.png',
      'genre' => 'Fantasy, Historical',
      'status' => 'Ongoing',
      'type' => 'TV Series',
      'rating' => '8.45',
      'episodes' => '157 episodes',
      'minutes_per_episode' => '24 min',
      'release_dates' => 'July 31, 2022 – Ongoing',
      'studio' => 'Motion Magic',
      'source' => 'Novel',
      'popularity_rank' => 6875,
      'rating_rank' => 171,
      'people_added' => '9.8K users',
      'description' => 'An immersive fantasy series filled with drama and adventure as characters navigate a historical fantasy world.'
    ],
    [
        'title' => 'Attack on Titan',
        'image' => 'res/animeCover/attackOnTitanS1.png',
        'genre' => 'Action, Mystery, Drama',
        'status' => 'Ongoing',
        'type' => 'TV Series',
        'rating' => '8.56',
        'episodes' => '25 episodes',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Apr 7, 2013 – Sept 29, 2013',
        'studio' => 'Wit Studio',
        'source' => 'Manga',
        'popularity_rank' => 1,
        'rating_rank' => 116,
        'people_added' => '4.1M users',
        'description' => 'Eren Yeager joins the Survey Corps to fight against the Titans after his city is destroyed and his mother is killed by a Titan.'
      ],
      [
        'title' => 'Death Note',
        'image' => 'res/animeCover/deathNote.png',
        'genre' => 'Mystery, Psychological, Thriller',
        'status' => 'Completed',
        'type' => 'TV Series',
        'rating' => '8.62',
        'episodes' => '37 episodes',
        'minutes_per_episode' => '23 min',
        'release_dates' => 'Oct 4, 2006 – Jun 27, 2007',
        'studio' => 'Madhouse',
        'source' => 'Manga',
        'popularity_rank' => 2,
        'rating_rank' => 89,
        'people_added' => '4.08M users',
        'description' => 'A high school student discovers a mysterious notebook that allows him to kill anyone by writing their name in it.'
      ],
      [
        'title' => 'Fullmetal Alchemist: Brotherhood',
        'image' => 'res/animeCover/fullMetalAlchemistBrotherhood.png',
        'genre' => 'Action, Adventure, Drama',
        'status' => 'Completed',
        'type' => 'TV Series',
        'rating' => '9.1',
        'episodes' => '64 episodes',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Apr 5, 2009 – Jul 4, 2010',
        'studio' => 'Bones',
        'source' => 'Manga',
        'popularity_rank' => 3,
        'rating_rank' => 2,
        'people_added' => '3.5M users',
        'description' => 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their mother goes awry and leaves them in damaged physical forms.'
      ],
      [
        'title' => 'One Punch Man',
        'image' => 'res/animeCover/onePunchManS1.png',
        'genre' => 'Action, Comedy, Superhero',
        'status' => 'Ongoing',
        'type' => 'TV Series',
        'rating' => '8.49',
        'episodes' => '12 episodes (Season 1)',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Oct 5, 2015 – Dec 21, 2015',
        'studio' => 'Madhouse',
        'source' => 'Manga',
        'popularity_rank' => 4,
        'rating_rank' => 150,
        'people_added' => '3.3M users',
        'description' => 'Saitama is a hero who can defeat anyone with a single punch, but he struggles with boredom from his overwhelming power.'
      ],
      [
        'title' => 'Demon Slayer: Kimetsu no Yaiba',
        'image' => 'res/animeCover/demonSlayerS1.png',
        'genre' => 'Action, Demons, Historical',
        'status' => 'Completed',
        'type' => 'TV Series',
        'rating' => '8.44',
        'episodes' => '26 episodes',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Apr 6, 2019 – Sep 28, 2019',
        'studio' => 'ufotable',
        'source' => 'Manga',
        'popularity_rank' => 5,
        'rating_rank' => 175,
        'people_added' => '3.2M users',
        'description' => 'After a demon attack leaves his family slain and his sister turned into a demon, Tanjiro Kamado sets out to become a demon slayer.'
      ],
      [
        'title' => 'Frieren: Beyond Journey\'s End',
        'image' => 'res/animeCover/frierenS1.png',
        'genre' => 'Fantasy, Adventure, Drama',
        'status' => 'Ongoing',
        'type' => 'TV Series',
        'rating' => '9.31',
        'episodes' => '28 episodes (Season 1)',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Sep 29, 2023 – March 22, 2024',
        'studio' => 'Madhouse',
        'source' => 'Manga',
        'popularity_rank' => 155,
        'rating_rank' => 1,
        'people_added' => '1.08M users',
        'description' => 'An elf mage reflects on her past adventures and the fleeting nature of human life after her companions\' death.'
      ],
      [
        'title' => 'Steins;Gate',
        'image' => 'res/animeCover/steinsGate.png',
        'genre' => 'Sci-Fi, Thriller, Drama',
        'status' => 'Completed',
        'type' => 'TV Series',
        'rating' => '9.07',
        'episodes' => '24 episodes',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Apr 6, 2011 – Sep 14, 2011',
        'studio' => 'White Fox',
        'source' => 'Visual Novel',
        'popularity_rank' => 14,
        'rating_rank' => 3,
        'people_added' => '2.6M users',
        'description' => 'A group of friends discovers time travel, leading to dangerous consequences as they try to fix the timeline.'
      ],
      [
        'title' => 'Attack on Titan Season 3 Part 2',
        'image' => 'res/animeCover/attackOnTitanS3P2.png',
        'genre' => 'Action, Mystery, Drama',
        'status' => 'Completed',
        'type' => 'TV Series',
        'rating' => '9.05',
        'episodes' => '10 episodes (Part 2)',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Apr 29, 2019 – July 01, 2019',
        'studio' => 'Wit Studio',
        'source' => 'Manga',
        'popularity_rank' => 21,
        'rating_rank' => 4,
        'people_added' => '2.4M users',
        'description' => 'The fight for humanity\'s survival against the Titans reaches a pivotal climax.'
      ],
      [
        'title' => 'One Piece: Fan Letter',
        'image' => 'res/animeCover/onePieceFanLetter.png',
        'genre' => 'Action, Adventure, Fantasy',
        'status' => 'Ongoing',
        'type' => 'TV Series (Special Episode)',
        'rating' => '9.05',
        'episodes' => '1 episode (Special)',
        'minutes_per_episode' => '24 min',
        'release_dates' => 'Oct 20, 2024',
        'studio' => 'Toei Animation',
        'source' => 'Manga',
        'popularity_rank' => 2210,
        'rating_rank' => 5,
        'people_added' => '102.1K users',
        'description' => 'A special episode celebrating the One Piece series with a heartfelt fan letter tribute to the fans.'
      ],
      [
        'title' => 'One-Punch Man Season 3',
        'image' => 'res/animeCover/onePunchManS3.png',
        'genre' => 'Action, Comedy, Superhero',
        'status' => 'Upcoming',
        'type' => 'TV Series',
        'rating' => 'N/A',
        'episodes' => 'N/A',
        'minutes_per_episode' => 'N/A',
        'release_dates' => 'Fall 2025',
        'studio' => 'J.C. Staff',
        'source' => 'Manga',
        'popularity_rank' => 929,
        'rating_rank' => 'N/A',
        'people_added' => '279.5K users',
        'description' => 'Saitama, the hero who can defeat any opponent with a single punch, faces new adversaries and challenges in the third season of this satirical superhero series.'
      ],
      [
        'title' => 'My Dress-Up Darling Season 2',
        'image' => 'res/animeCover/myDressUpDarlingS2.png',
        'genre' => 'Romance, Comedy, Slice of Life',
        'status' => 'Upcoming',
        'type' => 'TV Series',
        'rating' => 'N/A',
        'episodes' => 'N/A',
        'minutes_per_episode' => 'N/A',
        'release_dates' => 'Summer 2025',
        'studio' => 'CloverWorks',
        'source' => 'Manga',
        'popularity_rank' => 1456,
        'rating_rank' => 'N/A',
        'people_added' => '175.7K users',
        'description' => 'The story continues with Wakana and Marin navigating their relationship and diving deeper into the world of cosplay and self-expression in season 2 of this heartwarming romantic series.'
      ],
      [
        'title' => 'The Saga of Tanya the Evil Season 2',
        'image' => 'res/animeCover/sagaOfTanyaTheEvilS2.png',
        'genre' => 'Action, Fantasy, Military',
        'status' => 'Upcoming',
        'type' => 'TV Series',
        'rating' => 'N/A',
        'episodes' => 'N/A',
        'minutes_per_episode' => 'N/A',
        'release_dates' => 'N/A',
        'studio' => 'NuT',
        'source' => 'Light Novel',
        'popularity_rank' => 1490,
        'rating_rank' => 'N/A',
        'people_added' => '171.6K users',
        'description' => 'The ambitious and ruthless Tanya Degurechaff continues her journey through a war-torn alternate world, facing off against powerful foes in season 2 of this military fantasy series.'
      ],
      [
        'title' => 'Hell’s Paradise Season 2',
        'image' => 'res/animeCover/hellsParadiseS2.png',
        'genre' => 'Action, Supernatural, Adventure',
        'status' => 'Upcoming',
        'type' => 'TV Series',
        'rating' => 'N/A',
        'episodes' => 'N/A',
        'minutes_per_episode' => 'N/A',
        'release_dates' => 'Winter 2026',
        'studio' => 'MAPPA',
        'source' => 'Manga',
        'popularity_rank' => 1640,
        'rating_rank' => 'N/A',
        'people_added' => '152.2K users',
        'description' => 'The journey of the condemned criminals on a mystical island continues as they battle supernatural creatures and uncover the island’s dark secrets in the second season of this thrilling supernatural series.'
      ],
      [
        'title' => 'Frieren: Beyond Journey’s End Season 2',
        'image' => 'res/animeCover/frierenS2.png',
        'genre' => 'Fantasy, Adventure, Drama',
        'status' => 'Upcoming',
        'type' => 'TV Series',
        'rating' => 'N/A',
        'episodes' => 'N/A',
        'minutes_per_episode' => 'N/A',
        'release_dates' => 'Winter 2026',
        'studio' => 'Madhouse',
        'source' => 'Manga',
        'popularity_rank' => 1640,
        'rating_rank' => 'N/A',
        'people_added' => '152.2K users',
        'description' => 'Frieren, the elf mage, embarks on her own journey after her long-lasting companions pass on. As she reflects on her adventures, she grows in a world that changes around her. Season 2 continues the heart-wrenching and reflective story.'
      ]
  ];
?>